name: Create Banner Image

on: workflow_dispatch

jobs:
    create_banner_image:
        name: "Create Banner Image"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main
            - uses: darkterminal/create-banner-image@master # Uses an action in the root directory
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                canonical-name: 'banner'
                # gradient-colors: '#fc00ff,#00dbde'
                gradient-colors: '#cb04ff,#03de85'
                article-name: 'Miguel Pimentel'
                article-category: 'open-source'
                emoji: '🦝'
