name: Update Blog RSS Feed in README

on:
  workflow_dispatch:
  # schedule: [{ cron: 10 8 * * * }]

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update Blog RSS Feed in README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull RSS Entries
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://miguelpimentel.do/rss.xml"
          template: "$newline<tr><th>$date</th><td><a target='_blank' href='$url'>$title</a></td></tr>"
          date_format: "mmm d, yyyy"
          # feed_names: "Blog"
          # max_post_count: "5"
