name: Latest blog post workflow
on:
  workflow_dispatch: # Run workflow manually
  schedule: # Run workflow automatically
    - cron: '0 3 * * *' # Runs every day at 03:00

permissions:
  contents: write # Generated contents to README

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull Blog Posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          # feed_list: "https://miguelpimentel.do/feed.xml"
          feed_list: "https://miguelpimentel.do/rss.xml"
