name: Update Blog RSS Feed in README
on:
  workflow_dispatch: # Run workflow manually
  schedule: # Run workflow automatically
    - cron: '0 4 * * *' # Runs every day at 05:00

permissions:
  contents: write # Generated contents to README

jobs:
  update-readme-with-blog:
    name: Update Blog RSS Feed in README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull RSS Entries
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://miguelpimentel.do/rss.xml"
          template: "$newline- [$title]($url)"
          # feed_names: "Blog"
          # max_post_count: "5"
