name: Latest blog post workflow
on:
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour

permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull Blog Posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://miguelpimentel.do/en/feed.xml"
