name: Update GitHub Base Metrics SVG

on:
  # runs every Monday at 08:15
  schedule: [{ cron: "15 8 * * 1" }]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/svg/metrics-gh-base.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories
