name: Update GitHub Languages SVG

on:
on:
  # runs every Monday at 08:35
  schedule: [{ cron: "35 8 * * 1" }]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/svg/metrics-gh-languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: markdown
          plugin_languages_details: percentage
