# Source: https://github.com/lowlighter/metrics#-documentation
name: Update GitHub Languages

on:
  # runs every day at 04:15
  schedule: [{ cron: "15 4 * * *" }]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/svg/metrics-gh-languages.svg
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: markdown
          plugin_languages_details: percentage
