name: Update GitHub Mildly Interesting Facts SVG

on:
  # runs every Tuesday at 08:45
  schedule: [{ cron: "45 8 * * 2" }]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/svg/metrics-gh-mild-facts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          config_timezone: America/Chicago
