# Source: https://github.com/lowlighter/metrics#-documentation
name: Update GitHub Mildly Interesting Facts

on:
  # runs every day at 03:30
  # schedule: [{ cron: "40 3 * * *" }]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/svg/metrics-gh-mild-facts.svg
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          config_timezone: America/Chicago
