name: Update GitHub Notable Contributions SVG

on:
  # runs every Tuesday at 08:55
  schedule: [{ cron: "55 8 * * 2" }]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics-screenshot:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/svg/metrics-gh-notable-contributions.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_notable: yes
          plugin_notable_repositories: no
          plugin_notable_from: organization # opts: [all|organization|user]
          plugin_notable_types: commit, pull_request, issue
