name: Update Notes RSS Feed in README

on:
  workflow_dispatch:
  # schedule: [{ cron: 40 6 * * * }]

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update Notes RSS Feed in README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull RSS Entries
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://database.bearblog.dev/feed/?q=notes"
          template: "$newline- $date · [$title]($url)"
          comment_tag_name: "NOTES"
          date_format: "mmm d, yyyy"
          # feed_names: "Notes"
          # max_post_count: "5"
