name: Update Recent Activity (section) in Readme

on:
  # runs every Tuesday at 09:05
  schedule: [{ cron: "5 9 * * 2" }]
  workflow_dispatch:

jobs:
  build:
    name: Update Recent Activity
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update Recent GitHub Activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          MAX_LINES: 8
          COMMIT_MSG: "Update Recent Activity section in Readme"
          COMMIT_NAME: "Update GitHub Activity in Readme"
