name: Update Recent Activity in Readme

on:
  workflow_dispatch:
  # schedule: [{ cron: "10 */6 * * *" }]

jobs:
  build:
    name: Update Recent Activity
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update Recent GitHub Activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "Update Recent Activity section in README"
          MAX_LINES: 10
          COMMIT_NAME: Update GitHub Activity in Readme
