# Source: https://github.com/lowlighter/metrics#-documentation
name: Update Spotify - Top 10 (Artists)

on:
  # runs every day at 06:35
  # schedule: [{ cron: "35 6 * * *" }]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Spotify - Top 10 (Artists)
        uses: lowlighter/metrics@latest
        with:
          filename: assets/svg/metrics-spotify-top-artists.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_token: ${{ secrets.SPOTIFY_SECRETS }}
          plugin_music_mode: top
          plugin_music_limit: 10
          plugin_music_time_range: medium
          plugin_music_top_type: artists
          plugin_music_played_at: yes
