name: Update Tutorials RSS Feed in README
on:
  workflow_dispatch:
  # schedule: [{ cron: 10 22 * * * }]

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update Tutorials RSS Feed in README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull RSS Entries
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://miguelpimentel.do/rss-tutorials.xml"
          template: "$newline- $date · [$title]($url)"
          comment_tag_name: "TUTORIALS"
          date_format: "mmm d, yyyy"
          # feed_names: "Tutorials"
          # max_post_count: "5"
