name: Update Tutorials RSS Feed in README
on:
  workflow_dispatch: # Run workflow manually
  schedule: # Run workflow automatically
    - cron: 0 7 * * *

permissions:
  contents: write # Generated contents to README

jobs:
  update-readme-with-blog:
    name: Update Tutorials RSS Feed in README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull RSS Entries
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://database.bearblog.dev/feed/?q=tutorials"
          template: "$newline- $date · [$title]($url)"
          comment_tag_name: "TUTORIALS"
          # feed_names: "Tutorials"
          # max_post_count: "5"
