name: Update RSS entries in README
on:
  workflow_dispatch: # Run workflow manually
  schedule: # Run workflow automatically
    - cron: '0 3 * * *' # Runs every day at 03:00

permissions:
  contents: write # Generated contents to README

jobs:
  update-readme-with-blog:
    name: Update README with latest RSS entries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull RSS Entries
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          # feed_list: "https://miguelpimentel.do/rss.xml"
          feed_list: "https://miguelpimentel.do/rss.xml,https://miguelpimentel.do/notes.xml"
          feed_names: "Blog,Notes"
          max_post_count: "5"
          template: "$newline- [$feedName] [$title]($url)"
